version: '3'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - postgres
    command: ["./wait-for.sh", "postgres:5432", "-t", "600000", "--", "./app"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"